#!/usr/bin/env bash
#config nginx to have custom 404 page
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start

echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sudo sed -i '38i\error_page 404 /404.html;'  /etc/nginx/sites-enabled/default
sudo service nginx restart
