#!/usr/bin/env bash
#configures new web server with nginx configs

config_data='
server {
    listen 80 default_server;
    rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    listen [::]:80 default_server;

    error_page 404 /404.html;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;
    add_header X-Served-By $hostname;

    location / {
        try_files $uri $uri/ =404;
    }
}
'
apt update -y
apt install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$config_data" | sudo tee /etc/nginx/sites-enabled/default
nginx -s reload
