#!/usr/bin/env bash
# Configures a new web server with Nginx settings

apt update -y
apt install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i '/server_name _;/ a \\trewrite ^/redirect_me https://th3-gr00t.tk/ permanent;' /etc/nginx/sites-available/default
sed -i '/rewrite ^\/redirect_me https:\/\/th3-gr00t.tk\// a \\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default
nginx -s reload
