#!/usr/bin/env bash
#installs an configures haproxy
sudo apt update -y
sudo apt install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend balancer
    bind *:80
    mode http
    default_backend my-backend

backend my-backend
    balance roundrobin
    server 318867-web-01 100.26.210.219:80 check
    server 318867-web-02 52.207.139.38:80 check
EOL
sudo systemctl restart haproxy
sudo systemctl enable haproxy

