#!/usr/bin/env bash
#installs an configures haproxy
sudo apt update -y
sudo apt-get -y install haproxy

# Define the HAProxy configuration
server_config=\
"
frontend my_frontend
    bind *:80
    mode http
    default_backend my_backend
    timeout client 30s
    timeout connect 5s
    timeout server 30s

backend my_backend
    balance roundrobin
    mode http
	server 318867-web-01 100.26.210.219:80 check
    server 318867-web-02 52.207.139.38:80 check
    timeout client 30s 
    timeout connect 5s
    timeout server 30s
"
# Overwrite the HAProxy configuration file instead of appending
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Check the HAProxy configuration and restart HAProxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg && sudo service haproxy restart
