#!/usr/bin/env bash
#prints best school and then Hi on a new line
counter=0
while [ $counter -lt 10 ]
do
    echo "Best School"
    if [ $counter -eq 8 ]
    then
        echo "Hi"
    fi
    ((counter++))
done