#!/usr/bin/env bash
#prints content of current directory in list
for file in *; do
    if [[ ! "$file" =~ ^\. && -f "$file" ]]; then
        name=$(echo "$file" | cut -d'-' -f2-)
        echo "$name"
    fi
done