#!/usr/bin/env bash
#make nginx run as nginx user and listen on port 808
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen .*;$/listen 8080;/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
